### ISSUE TITLE
Feature request: add date field

### ISSUE THREAD

**Issue by ctuxboy** [GetSimpleCMS-CE/GetSimpleCMS-3.3.18#1]
Hello,

Nice that GetSimple still alive and developed continu actively.
Maybe a suggestion, adding a date field to Page Options , so it's possible planning when publish pages?

Regards,
Christophe

**Comment by risingisland** [comment]
Good idea. But at the moment we are just trying to fix php compatibility.

**Comment by ctuxboy** [comment]
> Good idea. But at the moment we are just trying to fix php compatibility.

I understand.
Awesome CMS the GS Community Edition.
Good work guys 🙏
